name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Navigate to project directory
        run: cd "Module 03/lab"

      - name: Create target directory
        run: mkdir -p target

      - name: Compile Java files
        run: javac -d target src/main/java/com/example/*.java

      - name: Run Java Application
        run: java -cp target com.example.App
