name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Navigate to project directory
        run: cd "Module 03\lab"

      - name: Create target directory
        run: mkdir target

      - name: Compile Java files
        run: javac -d target  C:\Users\snith\Lab3\Lab3-second\App.java
       
      - name: Run Java Application
        run: java -cp target com.example.App
